local hop = require('hop')
local directions = require('hop.hint').HintDirection
vim.keymap.set("n", 'f', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
end, {remap=true})
vim.keymap.set("n", 'F', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
end, {remap=true})
vim.keymap.set("n", "<leader><leader>w", function()
  hop.hint_words()
end, {remap=true})
vim.keymap.set("n", "<leader><leader>b", function()
  hop.hint_words({ direction = directions.BACKWARD })
end, {remap=true})
